version: '3'
services:
  backend:
    build:
      context: ./backend
    environment: 
      DB_NAME: postgres
      DB_SCHEMA: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./backend:/usr/src/
      - ./backend/node_modules/usr/src/node_modules # Remove this if you have pure JS dependencies
    ports:
      - 3000:3000
    depends_on: 
      - postgres
    container_name: backend
  frontend:
    build:
      context: ./frontend
    volumes:
      - "/usr/src/node_modules"
      - "./frontend:/usr/src"
    ports:
      - 4200:4200
    depends_on: 
      - postgres
    container_name: frontend
  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    container_name: postgres